name: Shauvik Roy Choudhary

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Shauvik <br /><small>Roy Choudhary</small>'
tagline:          'Entrepreneur & PhD'
description:      'Entrepreneur & PhD'
url:              http://shauvik.com

author:
  name:           'Shauvik Roy Choudhary'
  url:            https://twitter.com/shauvik

#paginate:         5

# Custom vars

ghurl:           https://github.com/shauvik
twitter:          https://twitter.com/shauvik
facebook:         https://facebook.com/shauvikr
linkedin:         https://linkedin.com/in/shauvik
